/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CptIndW */

#ifndef _Included_CptIndW
#define _Included_CptIndW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CptIndW
 * Method:    valeurCptIndW
 * Signature: (ILjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_CptIndW_valeurCptIndW
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
