/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CapteurLumineux_Windows */

#ifndef _Included_CapteurLumineux_Windows
#define _Included_CapteurLumineux_Windows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CapteurLumineux_Windows
 * Method:    valeurCapteurLumineux_Windows
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_CapteurLumineux_1Windows_valeurCapteurLumineux_1Windows
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
