/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CapteurLumineux */

#ifndef _Included_CapteurLumineux
#define _Included_CapteurLumineux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CapteurLumineux
 * Method:    valeurCapteurLumineux
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_CapteurLumineux_valeurCapteurLumineux
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
