/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CapteurInduction */

#ifndef _Included_CapteurInduction
#define _Included_CapteurInduction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CapteurInduction
 * Method:    valeurCapteurInduction
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_CapteurInduction_valeurCapteurInduction
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
