-- MySQL Script generated by MySQL Workbench
-- 03/07/17 12:50:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dupina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dupina` ;

-- -----------------------------------------------------
-- Schema dupina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dupina` DEFAULT CHARACTER SET utf8 ;
USE `dupina` ;

-- -----------------------------------------------------
-- Table `dupina`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dupina`.`user` ;

CREATE TABLE IF NOT EXISTS `dupina`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dupina`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dupina`.`post` ;

CREATE TABLE IF NOT EXISTS `dupina`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` LONGTEXT NULL,
  `date` DATETIME NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dupina`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dupina`.`category` ;

CREATE TABLE IF NOT EXISTS `dupina`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dupina`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `dupina`;
INSERT INTO `dupina`.`user` (`id`, `login`, `password`) VALUES (1, 'watchbot', '3390f0aa7176a43454748fdffd0649067933e089');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dupina`.`post`
-- -----------------------------------------------------
START TRANSACTION;
USE `dupina`;
INSERT INTO `dupina`.`post` (`id`, `title`, `content`, `date`, `category_id`) VALUES (1, 'Description de notre projet', 'L\'Apprentissage par Problèmes et par Projet est un module spécifique de la spécialité IAI (Instrumentation Automatique Informatique). Les élèves ont choisi le projet de Robotique de Service, s’étalant du semestre 6 au semestre 9. Ce projet est constitué d’une équipe de 11 élèves qui s’organisent de façon autonome. Cette année, le thème proposé est la télésurveillance robotisée. L’objectif est de parvenir à faire de la surveillance de bâtiments avec des robots autonomes afin qu’ils puissent interagir entre eux pour communiquer des informations. Pour cela, nous avons à disposition les robots Nao et Robotino. Ce module va donc nous permettre de travailler sur des robots et ainsi d’apprendre à les programmer par nous-mêmes.', NULL, 1);
INSERT INTO `dupina`.`post` (`id`, `title`, `content`, `date`, `category_id`) VALUES (2, 'Alan Dupin', 'J\'aime la programmation mais par dessus tout les cactus', NULL, 2);
INSERT INTO `dupina`.`post` (`id`, `title`, `content`, `date`, `category_id`) VALUES (3, 'Arnaud Mignotte', 'Magicien dans l\'ame</p><p>Je suis super délégué à Polytech et fais les meilleurs rapports de cette école', NULL, 2);
INSERT INTO `dupina`.`post` (`id`, `title`, `content`, `date`, `category_id`) VALUES (4, 'Jason Boileau', 'Gros geek de LoL et amateur de MF (Milf ou MissFortune)', NULL, 2);
INSERT INTO `dupina`.`post` (`id`, `title`, `content`, `date`, `category_id`) VALUES (5, 'Avancée du projet', 'Le projet avance bien mais nous sommes en train de résoudre des soucis sur la communication entre le serveur et robotino ainsi que sur le déplacement ', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dupina`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `dupina`;
INSERT INTO `dupina`.`category` (`id`, `title`) VALUES (1, 'Accueil');
INSERT INTO `dupina`.`category` (`id`, `title`) VALUES (2, 'Groupe');

COMMIT;

